apiVersion: v1
kind: Service

metadata:
  name: railwaygpt-frontend
  namespace: railwaygpt

spec:
  selector:
    app: railwaygpt-frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: NodePort