module.exports = {
  User: require('./User'),
  Train: require('./Train'),
  Route: require('./Route'),
  Booking: require('./Booking'),
  Ticket: require('./Ticket'),
  Payment: require('./Payment'),
  Notification: require('./Notification'),
  Conversation: require('./Conversation'),
  KnowledgeBase: require('./KnowledgeBase'),
  Embedding: require('./Embedding'),
  Agent: require('./Agent'),
  AgentLog: require('./AgentLog'),
  AuditLog: require('./AuditLog'),
  Session: require('./Session'),
  Transaction: require('./Transaction'),
  Document: require('./Document'),
  Review: require('./Review'),
  Feedback: require('./Feedback'),
  Prediction: require('./Prediction'),
};
