name: CI-CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  client:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: client
        run: npm ci

      - name: Build React App
        working-directory: client
        run: npm run build

  server:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: server
        run: npm ci

      - name: Run Tests
        working-directory: server
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          NODE_ENV: test
        run: npm test -- --ci

  docker:
    name: Build & Push Docker Images
    needs:
      - client
      - server

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        run: |
          docker build \
          -t vikashsharma0707/railwaygpt-backend:latest \
          ./server

      - name: Build Frontend Image
        run: |
          docker build \
          -t vikashsharma0707/railwaygpt-frontend:latest \
          ./client

      - name: Push Backend Image
        run: |
          docker push vikashsharma0707/railwaygpt-backend:latest

      - name: Push Frontend Image
        run: |
          docker push vikashsharma0707/railwaygpt-frontend:latest